name: Decojewel
description: Decojewel mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  mobile_scanner: ^7.1.3
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_typeahead: ^5.2.0
  permission_handler: ^12.0.1
  flutter_keyboard_visibility: ^6.0.0
  vibration: ^3.1.4
  # REMOVE characters, matcher, test_api, material_color_utilities

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/